### ISSUE TITLE
Vertical touch scrolling not working

### ISSUE THREAD

**Issue by hohwille** [ilbenstadt/ilbenstadt.github.io#2]
For whatever reason vertical scrolling is not possible via touch (swipe down/up):
https://ilbenstadt.github.io/
I can scroll with the mouse wheel or browser bar but for some reason not via swiping up or down.
It is working here:
https://icsd-summit.azurewebsites.net/
As I did not remove or modify the JS functionality except for removing navigation issues and the SVG logo I am clueless where this is coming from.

**Comment by hohwille** [comment]
Maybe one of these?
https://stackoverflow.com/questions/26611461/scroll-not-working-on-android-chrome-only
https://bugs.chromium.org/p/chromium/issues/detail?id=453065

**Comment by hohwille** [comment]
Very interesting is the fact that vertical scrolling via touch is working for the workshops/streams. But not in the agenda. What is going on here?

**Comment by markusschuh** [comment]
I assume, the following styles - which exist on the agenda, but not the workshop page - might block the vertical scrolling on touch devices:

element.style {
    touch-action: none;
    -webkit-user-drag: none;
}

Those seem to be introduced by some dependency (due to some different definitions for both pages within the app source code) - but I can't locate this dependency for the moment. I assume, generation of source-maps with help of karma should help to narrow down the root cause from this finding.

**Comment by hohwille** [comment]
@markusschuh Thanks for your excellent hint. I will dig from there to trace down the problem 👍

**Comment by hohwille** [comment]
Style does not come from CSS file but from dynamic JS:
```
        var Tt = M(c.style, "touchAction"),
          Ot = Tt !== a,
          kt = (function() {
            if (!Ot) return !1;
            var t = {},
              e = i.CSS && i.CSS.supports;
            return (
              [
                "auto",
                "manipulation",
                "pan-y",
                "pan-x",
                "pan-x pan-y",
                "none"
              ].forEach(function(n) {
                t[n] = !e || i.CSS.supports("touch-action", n);
              }),
              t
            );
```

I have to trace this down to the source that is causing this.

**Comment by hohwille** [comment]
`<div _ngcontent-c9="" style="touch-action: none; -moz-user-select: none;" class="ng-star-inserted">`

**Comment by hohwille** [comment]
fixed.
